// ai-cs-frontend/src/views/OrderView.vue
<template>
  <div class="order-view">
    <h2>我的订单</h2>

    <el-table :data="orders" style="width: 100%" @row-click="goDetail" row-class-name="clickable">
      <el-table-column prop="orderNo" label="订单号" min-width="180" />
      <el-table-column label="状态" width="110">
        <template #default="{ row }">
          <el-tag :type="statusTag(row.status)">{{ statusText(row.status) }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="商品" min-width="200">
        <template #default="{ row }">
          <span>{{ (row.items || []).map(i => `${i.productName}×${i.quantity}`).join('、') || '-' }}</span>
        </template>
      </el-table-column>
      <el-table-column label="应付金额" width="120">
        <template #default="{ row }">¥{{ Number(row.payAmount || 0).toFixed(2) }}</template>
      </el-table-column>
      <el-table-column label="下单时间" width="170">
        <template #default="{ row }">{{ formatTime(row.createTime) }}</template>
      </el-table-column>
      <el-table-column label="操作" width="110">
        <template #default="{ row }">
          <el-button type="primary" size="small" link @click.stop="goDetail(row)">详情</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-empty v-if="!orders.length" description="暂无订单" />
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { orderApi } from '../api'
import { getUser } from '../utils/auth'

const router = useRouter()
const userId = ref(getUser()?.userId || localStorage.getItem('userId') || '')
const orders = ref([])

onMounted(fetchOrders)

async function fetchOrders() {
  try {
    const { data } = await orderApi.get('/list', { headers: { 'X-User-Id': userId.value } })
    if (data.code === 200) {
      orders.value = data.data || []
    } else {
      ElMessage.error(data.message)
    }
  } catch (e) {
    ElMessage.error('获取订单列表失败')
  }
}

function goDetail(row) {
  router.push(`/order/${row.orderNo}`)
}

function statusText(status) {
  const map = { PENDING_PAY: '待支付', PAID: '已支付', CANCELLED: '已取消' }
  return map[status] || status
}

function statusTag(status) {
  const map = { PENDING_PAY: 'warning', PAID: 'success', CANCELLED: 'info' }
  return map[status] || 'info'
}

function formatTime(t) {
  return t ? String(t).replace('T', ' ').slice(0, 19) : '-'
}
</script>

<style scoped>
.order-view { padding: 20px; }
.clickable { cursor: pointer; }
</style>

// ai-cs-frontend-react/src/views/OrderView.jsx
import { useEffect, useState } from 'react'
import { Button, Empty, Table, Tag, message } from 'antd'
import { useNavigate } from 'react-router-dom'
import { orderApi } from '../api'
import { getUser } from '../utils/auth'
import { formatTime, statusTag, statusText } from '../utils/order'

export default function OrderView() {
  const navigate = useNavigate()
  const userId = getUser()?.userId || localStorage.getItem('userId') || ''
  const [orders, setOrders] = useState([])

  useEffect(() => {
    fetchOrders()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function fetchOrders() {
    try {
      const { data } = await orderApi.get('/list', { headers: { 'X-User-Id': userId } })
      if (data.code === 200) {
        setOrders(data.data || [])
      } else {
        message.error(data.message)
      }
    } catch {
      message.error('获取订单列表失败')
    }
  }

  function goDetail(row) {
    navigate(`/order/${row.orderNo}`)
  }

  const columns = [
    { title: '订单号', dataIndex: 'orderNo', minWidth: 180 },
    {
      title: '状态',
      width: 110,
      render: (_, row) => <Tag color={statusTag(row.status)}>{statusText(row.status)}</Tag>,
    },
    {
      title: '商品',
      minWidth: 200,
      render: (_, row) =>
        (row.items || []).map((i) => `${i.productName}×${i.quantity}`).join('、') || '-',
    },
    {
      title: '应付金额',
      width: 120,
      render: (_, row) => `¥${Number(row.payAmount || 0).toFixed(2)}`,
    },
    {
      title: '下单时间',
      width: 170,
      render: (_, row) => formatTime(row.createTime),
    },
    {
      title: '操作',
      width: 110,
      render: (_, row) => (
        <Button
          type="link"
          size="small"
          onClick={(e) => {
            e.stopPropagation()
            goDetail(row)
          }}
        >
          详情
        </Button>
      ),
    },
  ]

  return (
    <div className="order-view">
      <h2>我的订单</h2>

      <Table
        rowKey="orderNo"
        className="clickable"
        columns={columns}
        dataSource={orders}
        style={{ marginTop: 16 }}
        pagination={false}
        onRow={(row) => ({ onClick: () => goDetail(row) })}
        locale={{ emptyText: <Empty description="暂无订单" /> }}
      />
    </div>
  )
}
