// ai-cs-frontend/src/views/SearchView.vue
<template>
  <div class="search-view">
    <el-row :gutter="20">
      <el-col :span="16">
        <el-card shadow="hover">
          <template #header><span style="font-weight: 600">全文搜索 (Chroma)</span></template>

          <div style="display: flex; gap: 10px; margin-bottom: 20px">
            <el-input v-model="indexName" placeholder="索引名称" style="width: 200px" />
            <el-input v-model="searchQuery" placeholder="搜索关键词..." clearable style="flex: 1" @keydown.enter="doSearch" />
            <el-button type="primary" @click="doSearch" :loading="searching" :icon="Search">搜索</el-button>
          </div>

          <!-- 搜索结果 -->
          <div v-if="results.length > 0" class="result-list">
            <div v-for="(item, i) in results" :key="i" class="result-item">
              <div class="result-title">{{ item.title || item._id || '文档 ' + (i + 1) }}</div>
              <div class="result-content">{{ item.content || item.highlight || JSON.stringify(item) }}</div>
              <div class="result-meta">
                <el-tag size="small" type="info">{{ item._index || indexName }}</el-tag>
                <span class="result-score" v-if="item._score">相关度: {{ item._score?.toFixed(2) }}</span>
              </div>
            </div>
          </div>
          <el-empty v-else-if="searched" description="未找到相关结果" />
        </el-card>
      </el-col>

      <el-col :span="8">
        <el-card shadow="hover">
          <template #header><span style="font-weight: 600">索引管理</span></template>

          <el-form label-width="80px">
            <el-form-item label="索引名称">
              <el-input v-model="indexMgmt.name" placeholder="索引名称" />
            </el-form-item>
            <el-form-item>
              <el-button type="primary" @click="createIndex" :icon="Plus">创建索引</el-button>
              <el-popconfirm title="确认删除索引?" @confirm="deleteIndex">
                <template #reference>
                  <el-button type="danger" :icon="Delete">删除索引</el-button>
                </template>
              </el-popconfirm>
            </el-form-item>
          </el-form>
        </el-card>

        <el-card shadow="hover" style="margin-top: 20px">
          <template #header><span style="font-weight: 600">索引文档</span></template>
          <el-form label-width="80px">
            <el-form-item label="索引名称">
              <el-input v-model="docIndex.name" placeholder="索引名称" />
            </el-form-item>
            <el-form-item label="文档内容">
              <el-input v-model="docIndex.content" type="textarea" :rows="5" placeholder='JSON 格式，如 {"title":"xxx","content":"xxx"}' />
            </el-form-item>
            <el-form-item>
              <el-button type="success" @click="indexDoc" :icon="Document">索引文档</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { searchApi } from '../api'
import { ElMessage } from 'element-plus'
import { Search, Plus, Delete, Document } from '@element-plus/icons-vue'

const indexName = ref('knowledge')
const searchQuery = ref('')
const results = ref([])
const searching = ref(false)
const searched = ref(false)
const page = ref(1)

const indexMgmt = ref({ name: '' })
const docIndex = ref({ name: '', content: '' })

async function doSearch() {
  if (!searchQuery.value.trim()) return
  searching.value = true
  searched.value = true
  try {
    const res = await searchApi.get(`/${indexName.value}`, {
      params: { query: searchQuery.value, page: page.value, size: 20 }
    })
    results.value = res.data?.data || []
    ElMessage.success(`找到 ${results.value.length} 条结果`)
  } catch (e) {
    results.value = []
    ElMessage.error('搜索失败: ' + (e.response?.data?.message || e.message))
  } finally {
    searching.value = false
  }
}

async function createIndex() {
  if (!indexMgmt.value.name) return ElMessage.warning('请输入索引名称')
  try {
    await searchApi.post(`/index/${indexMgmt.value.name}`, {})
    ElMessage.success('索引创建成功')
  } catch (e) {
    ElMessage.error('创建失败: ' + (e.response?.data?.message || e.message))
  }
}

async function deleteIndex() {
  if (!indexMgmt.value.name) return ElMessage.warning('请输入索引名称')
  try {
    await searchApi.delete(`/index/${indexMgmt.value.name}`)
    ElMessage.success('索引删除成功')
  } catch (e) {
    ElMessage.error('删除失败: ' + (e.response?.data?.message || e.message))
  }
}

async function indexDoc() {
  if (!docIndex.value.name || !docIndex.value.content) return ElMessage.warning('请填写完整')
  try {
    const doc = JSON.parse(docIndex.value.content)
    await searchApi.post(`/document/${docIndex.value.name}`, doc)
    ElMessage.success('文档索引成功')
    docIndex.value.content = ''
  } catch (e) {
    if (e instanceof SyntaxError) return ElMessage.error('文档内容必须是合法 JSON')
    ElMessage.error('索引失败: ' + (e.response?.data?.message || e.message))
  }
}
</script>

<style scoped>
.result-list { display: flex; flex-direction: column; gap: 16px; }
.result-item { padding: 16px; background: #fafafa; border-radius: 8px; border-left: 4px solid #409eff; }
.result-title { font-size: 16px; font-weight: 600; color: #1d1e2c; margin-bottom: 6px; }
.result-content { font-size: 14px; color: #606266; line-height: 1.6; margin-bottom: 8px; }
.result-meta { display: flex; align-items: center; gap: 10px; }
.result-score { font-size: 12px; color: #909399; }
</style>

// ai-cs-frontend-react/src/views/SearchView.jsx
import { useState } from 'react'
import { Button, Card, Col, Empty, Form, Input, Popconfirm, Row, Tag, message } from 'antd'
import { DeleteOutlined, FileTextOutlined, PlusOutlined, SearchOutlined } from '@ant-design/icons'
import { searchApi } from '../api'

export default function SearchView() {
  const [indexName, setIndexName] = useState('knowledge')
  const [searchQuery, setSearchQuery] = useState('')
  const [results, setResults] = useState([])
  const [searching, setSearching] = useState(false)
  const [searched, setSearched] = useState(false)
  const [page] = useState(1)

  const [indexMgmt, setIndexMgmt] = useState({ name: '' })
  const [docIndex, setDocIndex] = useState({ name: '', content: '' })

  async function doSearch() {
    if (!searchQuery.trim()) return
    setSearching(true)
    setSearched(true)
    try {
      const res = await searchApi.get(`/${indexName}`, {
        params: { query: searchQuery, page, size: 20 },
      })
      const list = res.data?.data || []
      setResults(list)
      message.success(`找到 ${list.length} 条结果`)
    } catch (e) {
      setResults([])
      message.error('搜索失败: ' + (e.response?.data?.message || e.message))
    } finally {
      setSearching(false)
    }
  }

  async function createIndex() {
    if (!indexMgmt.name) {
      message.warning('请输入索引名称')
      return
    }
    try {
      await searchApi.post(`/index/${indexMgmt.name}`, {})
      message.success('索引创建成功')
    } catch (e) {
      message.error('创建失败: ' + (e.response?.data?.message || e.message))
    }
  }

  async function deleteIndex() {
    if (!indexMgmt.name) {
      message.warning('请输入索引名称')
      return
    }
    try {
      await searchApi.delete(`/index/${indexMgmt.name}`)
      message.success('索引删除成功')
    } catch (e) {
      message.error('删除失败: ' + (e.response?.data?.message || e.message))
    }
  }

  async function indexDoc() {
    if (!docIndex.name || !docIndex.content) {
      message.warning('请填写完整')
      return
    }
    let doc
    try {
      doc = JSON.parse(docIndex.content)
    } catch {
      message.error('文档内容必须是合法 JSON')
      return
    }
    try {
      await searchApi.post(`/document/${docIndex.name}`, doc)
      message.success('文档索引成功')
      setDocIndex((p) => ({ ...p, content: '' }))
    } catch (e) {
      message.error('索引失败: ' + (e.response?.data?.message || e.message))
    }
  }

  return (
    <div className="search-view">
      <Row gutter={20}>
        <Col span={16}>
          <Card hoverable title={<span style={{ fontWeight: 600 }}>全文搜索 (Chroma)</span>}>
            <div style={{ display: 'flex', gap: 10, marginBottom: 20 }}>
              <Input
                value={indexName}
                onChange={(e) => setIndexName(e.target.value)}
                placeholder="索引名称"
                style={{ width: 200 }}
              />
              <Input
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="搜索关键词..."
                allowClear
                style={{ flex: 1 }}
                onPressEnter={doSearch}
              />
              <Button type="primary" icon={<SearchOutlined />} loading={searching} onClick={doSearch}>
                搜索
              </Button>
            </div>

            {/* 搜索结果 */}
            {results.length > 0 ? (
              <div className="result-list">
                {results.map((item, i) => (
                  <div className="result-item" key={i}>
                    <div className="result-title">{item.title || item._id || '文档 ' + (i + 1)}</div>
                    <div className="result-content">
                      {item.content || item.highlight || JSON.stringify(item)}
                    </div>
                    <div className="result-meta">
                      <Tag>{item._index || indexName}</Tag>
                      {item._score ? (
                        <span className="result-score">相关度: {item._score?.toFixed(2)}</span>
                      ) : null}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              searched && <Empty description="未找到相关结果" />
            )}
          </Card>
        </Col>

        <Col span={8}>
          <Card hoverable title={<span style={{ fontWeight: 600 }}>索引管理</span>}>
            <Form labelCol={{ span: 6 }} wrapperCol={{ span: 18 }}>
              <Form.Item label="索引名称">
                <Input
                  value={indexMgmt.name}
                  onChange={(e) => setIndexMgmt({ name: e.target.value })}
                  placeholder="索引名称"
                />
              </Form.Item>
              <Form.Item wrapperCol={{ offset: 6, span: 18 }}>
                <Button type="primary" icon={<PlusOutlined />} onClick={createIndex}>
                  创建索引
                </Button>
                <Popconfirm title="确认删除索引?" onConfirm={deleteIndex}>
                  <Button danger icon={<DeleteOutlined />} style={{ marginLeft: 10 }}>
                    删除索引
                  </Button>
                </Popconfirm>
              </Form.Item>
            </Form>
          </Card>

          <Card hoverable style={{ marginTop: 20 }} title={<span style={{ fontWeight: 600 }}>索引文档</span>}>
            <Form labelCol={{ span: 6 }} wrapperCol={{ span: 18 }}>
              <Form.Item label="索引名称">
                <Input
                  value={docIndex.name}
                  onChange={(e) => setDocIndex((p) => ({ ...p, name: e.target.value }))}
                  placeholder="索引名称"
                />
              </Form.Item>
              <Form.Item label="文档内容">
                <Input.TextArea
                  value={docIndex.content}
                  onChange={(e) => setDocIndex((p) => ({ ...p, content: e.target.value }))}
                  rows={5}
                  placeholder='JSON 格式，如 {"title":"xxx","content":"xxx"}'
                />
              </Form.Item>
              <Form.Item wrapperCol={{ offset: 6, span: 18 }}>
                <Button type="primary" icon={<FileTextOutlined />} onClick={indexDoc}>
                  索引文档
                </Button>
              </Form.Item>
            </Form>
          </Card>
        </Col>
      </Row>
    </div>
  )
}
