// ai-cs-frontend-react/src/views/MessageView.jsx
import { useState } from 'react'
import { Button, Card, Col, Form, Input, InputNumber, Row, Table, Tag, message } from 'antd'
import { PlusOutlined, ReloadOutlined, SendOutlined } from '@ant-design/icons'
import { messageApi } from '../api'

export default function MessageView() {
  const [userId, setUserId] = useState(1)
  const [sessionTitle, setSessionTitle] = useState('新会话')
  const [sessions, setSessions] = useState([])
  const [selectedSessionMessages, setSelectedSessionMessages] = useState([])
  const [msgForm, setMsgForm] = useState({ sessionId: '', content: '', role: 'user' })

  async function createSession() {
    try {
      await messageApi.post('/session', null, {
        params: { userId, title: sessionTitle },
      })
      message.success('会话创建成功')
      fetchSessions()
    } catch (e) {
      message.error('创建失败: ' + (e.response?.data?.message || e.message))
    }
  }

  async function sendMessage() {
    try {
      await messageApi.post('/send', msgForm)
      message.success('消息已发送')
      setMsgForm((prev) => ({ ...prev, content: '' }))
    } catch (e) {
      message.error('发送失败: ' + (e.response?.data?.message || e.message))
    }
  }

  async function fetchSessions() {
    try {
      const res = await messageApi.get('/sessions', { params: { userId } })
      setSessions(res.data?.data || [])
    } catch (e) {
      message.error('加载会话列表失败: ' + (e.response?.data?.message || e.message))
    }
  }

  async function viewMessages(sessionId) {
    try {
      const res = await messageApi.get(`/session/${sessionId}/messages`)
      setSelectedSessionMessages(res.data?.data || [])
    } catch (e) {
      message.error('加载消息失败: ' + (e.response?.data?.message || e.message))
    }
  }

  const columns = [
    { title: 'ID', dataIndex: 'id', width: 80 },
    { title: '标题', dataIndex: 'title' },
    { title: '用户ID', dataIndex: 'userId', width: 80 },
    { title: '创建时间', dataIndex: 'createTime', width: 180 },
    {
      title: '操作',
      width: 120,
      render: (_, row) => (
        <Button size="small" type="primary" onClick={() => viewMessages(row.id)}>
          查看消息
        </Button>
      ),
    },
  ]

  return (
    <div className="message-view">
      <Row gutter={20}>
        <Col span={10}>
          <Card hoverable title={<span style={{ fontWeight: 600 }}>创建会话</span>}>
            <Form layout="inline">
              <Form.Item label="用户ID">
                <InputNumber min={1} value={userId} onChange={(v) => setUserId(v ?? 1)} />
              </Form.Item>
              <Form.Item label="标题">
                <Input
                  value={sessionTitle}
                  onChange={(e) => setSessionTitle(e.target.value)}
                  placeholder="会话标题"
                />
              </Form.Item>
              <Form.Item>
                <Button type="primary" icon={<PlusOutlined />} onClick={createSession}>
                  创建
                </Button>
              </Form.Item>
            </Form>
          </Card>

          <Card hoverable style={{ marginTop: 20 }} title={<span style={{ fontWeight: 600 }}>发送消息 (RocketMQ)</span>}>
            <Form labelCol={{ span: 5 }} wrapperCol={{ span: 19 }}>
              <Form.Item label="会话ID">
                <Input
                  value={msgForm.sessionId}
                  onChange={(e) => setMsgForm((p) => ({ ...p, sessionId: e.target.value }))}
                  placeholder="会话ID"
                />
              </Form.Item>
              <Form.Item label="内容">
                <Input.TextArea
                  value={msgForm.content}
                  onChange={(e) => setMsgForm((p) => ({ ...p, content: e.target.value }))}
                  rows={3}
                  placeholder="消息内容"
                />
              </Form.Item>
              <Form.Item wrapperCol={{ offset: 5, span: 19 }}>
                <Button type="primary" icon={<SendOutlined />} onClick={sendMessage}>
                  发送
                </Button>
              </Form.Item>
            </Form>
          </Card>
        </Col>

        <Col span={14}>
          <Card
            hoverable
            title={
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontWeight: 600 }}>会话列表</span>
                <Button size="small" icon={<ReloadOutlined />} onClick={fetchSessions}>
                  刷新
                </Button>
              </div>
            }
          >
            <Table
              rowKey="id"
              columns={columns}
              dataSource={sessions}
              bordered
              pagination={false}
            />
          </Card>

          {selectedSessionMessages.length > 0 && (
            <Card hoverable style={{ marginTop: 20 }} title={<span style={{ fontWeight: 600 }}>会话消息</span>}>
              <div className="msg-list">
                {selectedSessionMessages.map((msg) => (
                  <div className="msg-item" key={msg.id}>
                    <Tag color={msg.role === 'user' ? undefined : 'success'}>{msg.role || '消息'}</Tag>
                    <span>{msg.content}</span>
                  </div>
                ))}
              </div>
            </Card>
          )}
        </Col>
      </Row>
    </div>
  )
}

// ai-cs-frontend/src/views/MessageView.vue
<template>
  <div class="message-view">
    <el-row :gutter="20">
      <el-col :span="10">
        <el-card shadow="hover">
          <template #header><span style="font-weight: 600">创建会话</span></template>
          <el-form :inline="true">
            <el-form-item label="用户ID">
              <el-input-number v-model="userId" :min="1" />
            </el-form-item>
            <el-form-item label="标题">
              <el-input v-model="sessionTitle" placeholder="会话标题" />
            </el-form-item>
            <el-form-item>
              <el-button type="primary" @click="createSession" :icon="Plus">创建</el-button>
            </el-form-item>
          </el-form>
        </el-card>

        <el-card shadow="hover" style="margin-top: 20px">
          <template #header><span style="font-weight: 600">发送消息 (RocketMQ)</span></template>
          <el-form :model="msgForm" label-width="80px">
            <el-form-item label="会话ID">
              <el-input v-model="msgForm.sessionId" placeholder="会话ID" />
            </el-form-item>
            <el-form-item label="内容">
              <el-input v-model="msgForm.content" type="textarea" :rows="3" placeholder="消息内容" />
            </el-form-item>
            <el-form-item>
              <el-button type="primary" @click="sendMessage" :icon="Promotion">发送</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </el-col>

      <el-col :span="14">
        <el-card shadow="hover">
          <template #header>
            <div style="display: flex; justify-content: space-between; align-items: center">
              <span style="font-weight: 600">会话列表</span>
              <el-button size="small" @click="fetchSessions" :icon="Refresh">刷新</el-button>
            </div>
          </template>
          <el-table :data="sessions" border stripe>
            <el-table-column prop="id" label="ID" width="80" />
            <el-table-column prop="title" label="标题" />
            <el-table-column prop="userId" label="用户ID" width="80" />
            <el-table-column prop="createTime" label="创建时间" width="180" />
            <el-table-column label="操作" width="120">
              <template #default="{ row }">
                <el-button size="small" type="primary" @click="viewMessages(row.id)">查看消息</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-card>

        <el-card shadow="hover" style="margin-top: 20px" v-if="selectedSessionMessages.length > 0">
          <template #header><span style="font-weight: 600">会话消息</span></template>
          <div class="msg-list">
            <div v-for="msg in selectedSessionMessages" :key="msg.id" class="msg-item">
              <el-tag :type="msg.role === 'user' ? '' : 'success'" size="small">{{ msg.role || '消息' }}</el-tag>
              <span>{{ msg.content }}</span>
            </div>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { messageApi } from '../api'
import { ElMessage } from 'element-plus'
import { Plus, Promotion, Refresh } from '@element-plus/icons-vue'

const userId = ref(1)
const sessionTitle = ref('新会话')
const sessions = ref([])
const selectedSessionMessages = ref([])
const msgForm = ref({ sessionId: '', content: '', role: 'user' })

async function createSession() {
  try {
    const res = await messageApi.post('/session', null, { params: { userId: userId.value, title: sessionTitle.value } })
    ElMessage.success('会话创建成功')
    fetchSessions()
  } catch (e) {
    ElMessage.error('创建失败: ' + (e.response?.data?.message || e.message))
  }
}

async function sendMessage() {
  try {
    await messageApi.post('/send', msgForm.value)
    ElMessage.success('消息已发送')
    msgForm.value.content = ''
  } catch (e) {
    ElMessage.error('发送失败: ' + (e.response?.data?.message || e.message))
  }
}

async function fetchSessions() {
  try {
    const res = await messageApi.get('/sessions', { params: { userId: userId.value } })
    sessions.value = res.data?.data || []
  } catch (e) {
    ElMessage.error('加载会话列表失败: ' + (e.response?.data?.message || e.message))
  }
}

async function viewMessages(sessionId) {
  try {
    const res = await messageApi.get(`/session/${sessionId}/messages`)
    selectedSessionMessages.value = res.data?.data || []
  } catch (e) {
    ElMessage.error('加载消息失败: ' + (e.response?.data?.message || e.message))
  }
}
</script>

<style scoped>
.msg-list { display: flex; flex-direction: column; gap: 10px; max-height: 400px; overflow-y: auto; }
.msg-item { display: flex; align-items: center; gap: 10px; padding: 8px 12px; background: #fafafa; border-radius: 6px; }
</style>
