// ai-cs-frontend-react/src/views/ShopView.jsx
import { useEffect, useState } from 'react'
import { Alert, Badge, Button, Card, Col, Empty, Input, InputNumber, Pagination, Row, Select, Spin, Tag, message } from 'antd'
import { CreditCardOutlined, ProfileOutlined, SearchOutlined, ShoppingCartOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { cartApi, productApi } from '../api'
import { getUser } from '../utils/auth'

export default function ShopView() {
  const navigate = useNavigate()

  const [products, setProducts] = useState([])
  const [categories, setCategories] = useState([])
  const [keyword, setKeyword] = useState('')
  const [searchMode, setSearchMode] = useState('keyword')
  const [categoryId, setCategoryId] = useState(null)
  const [page, setPage] = useState(1)
  const [size] = useState(12)
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(false)
  const [cartCount, setCartCount] = useState(0)
  const [addingId, setAddingId] = useState(null)
  const [qtyMap, setQtyMap] = useState({})

  const userId = getUser()?.userId || ''

  useEffect(() => {
    loadCategories()
    loadCartCount()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    loadProducts()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page])

  async function loadCategories() {
    try {
      const { data } = await productApi.get('/categories')
      if (data.code === 200) setCategories(data.data || [])
    } catch {
      // 分类加载失败不阻塞页面
    }
  }

  async function loadProducts() {
    setLoading(true)
    try {
      if (searchMode === 'semantic' && keyword.trim()) {
        const { data } = await productApi.get('/similar', {
          params: { text: keyword.trim(), topK: 12 },
        })
        if (data.code === 200) {
          const list = (data.data || []).map((r) => ({
            id: r.productId,
            name: r.name,
            price: r.price,
            image: r.image,
            stock: undefined,
            score: r.score,
          }))
          setProducts(list)
          setTotal(list.length)
        }
      } else {
        const params = { page, size, status: 1 }
        if (keyword.trim()) params.keyword = keyword.trim()
        if (categoryId) params.categoryId = categoryId
        const { data } = await productApi.get('/list', { params })
        if (data.code === 200 && data.data) {
          setProducts(data.data.records || [])
          setTotal(data.data.total || 0)
        }
      }
    } catch {
      message.error('加载商品失败')
    } finally {
      setLoading(false)
    }
  }

  function handleSearch() {
    if (page !== 1) setPage(1)
    else loadProducts()
  }

  async function addToCart(p) {
    const qty = qtyMap[p.id] || 1
    setAddingId(p.id)
    try {
      const { data } = await cartApi.post(
        '/add',
        { productId: p.id, quantity: qty },
        { headers: { 'X-User-Id': userId } }
      )
      if (data.code === 200) {
        message.success(`「${p.name}」已加入购物车`)
        loadCartCount()
        loadProducts() // 刷新商城库存，实时反映扣减（库存以商品服务 DB 为权威源）
      } else {
        message.error(data.message || '加入购物车失败')
      }
    } catch (e) {
      message.error(e.response?.data?.message || '加入购物车失败')
    } finally {
      setAddingId(null)
    }
  }

  async function loadCartCount() {
    try {
      const { data } = await cartApi.get('/list', { headers: { 'X-User-Id': userId } })
      if (data.code === 200) setCartCount((data.data?.items || []).length)
    } catch {
      // 忽略
    }
  }

  return (
    <div className="shop-view">
      <div className="shop-toolbar">
        <div className="toolbar-left">
          <h2>商品商城</h2>
          <Select
            value={searchMode}
            onChange={setSearchMode}
            style={{ width: 128 }}
            options={[
              { label: '关键词搜索', value: 'keyword' },
              { label: '语义搜索', value: 'semantic' },
            ]}
          />
          <Input
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            placeholder="搜索商品名称 / 描述，回车搜索"
            allowClear
            style={{ width: 260 }}
            onPressEnter={handleSearch}
          />
          <Select
            value={categoryId}
            onChange={(v) => {
              setCategoryId(v ?? null)
              handleSearch()
            }}
            placeholder="全部分类"
            allowClear
            style={{ width: 140 }}
            options={categories.map((c) => ({ label: c.name, value: c.id }))}
          />
          <Button type="primary" icon={<SearchOutlined />} loading={loading} onClick={handleSearch}>
            搜索
          </Button>
        </div>
        <div className="toolbar-right">
          <Badge count={cartCount} className="cart-badge">
            <Button icon={<ShoppingCartOutlined />} onClick={() => navigate('/cart')}>
              购物车
            </Button>
          </Badge>
          <Button icon={<ProfileOutlined />} onClick={() => navigate('/order')}>
            我的订单
          </Button>
          <Button type="primary" icon={<CreditCardOutlined />} onClick={() => navigate('/cart')}>
            去结算
          </Button>
        </div>
      </div>

      <Alert
        type="info"
        showIcon
        style={{ marginBottom: 16 }}
        message="支付流程体验：购物车 → 结算 → 下单 → 订单详情「立即支付」→ 模拟收银台 → 支付成功（含渠道回调 / 验签 / 幂等状态更新）。"
      />

      <Spin spinning={loading}>
        {!loading && products.length === 0 && <Empty description="暂无商品" />}
        <Row gutter={16}>
          {products.map((p) => (
            <Col span={6} key={p.id} style={{ marginBottom: 16 }}>
              <Card hoverable className="product-card" styles={{ body: { padding: 0 } }}>
                <div className="product-img-box">
                  {p.image ? (
                    <img src={p.image} className="img" alt={p.name} />
                  ) : (
                    <div className="img-placeholder">暂无图片</div>
                  )}
                </div>
                <div className="product-body">
                  <div className="product-name" title={p.name}>
                    {p.name}
                  </div>
                  <div className="product-meta">
                    <span className="price">¥{Number(p.price).toFixed(2)}</span>
                    {p.stock !== undefined && <span className="stock">库存 {p.stock}</span>}
                    {p.score !== undefined && (
                      <Tag color="success">相似度 {Number(p.score).toFixed(4)}</Tag>
                    )}
                  </div>
                  <div className="product-actions">
                    <InputNumber
                      min={1}
                      max={99}
                      size="small"
                      value={qtyMap[p.id] ?? 1}
                      onChange={(v) => setQtyMap((prev) => ({ ...prev, [p.id]: v ?? 1 }))}
                    />
                    <Button
                      type="primary"
                      size="small"
                      loading={addingId === p.id}
                      onClick={() => addToCart(p)}
                    >
                      加入购物车
                    </Button>
                  </div>
                </div>
              </Card>
            </Col>
          ))}
        </Row>
      </Spin>

      {total > size && (
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <Pagination
            className="pager"
            current={page}
            pageSize={size}
            total={total}
            showTotal={(t) => `共 ${t} 条`}
            onChange={(p) => setPage(p)}
          />
        </div>
      )}
    </div>
  )
}

// ai-cs-frontend/src/views/ShopView.vue
<template>
  <div class="shop-view">
    <div class="shop-toolbar">
      <div class="toolbar-left">
        <h2>商品商城</h2>
        <el-select v-model="searchMode" style="width: 128px">
          <el-option label="关键词搜索" value="keyword" />
          <el-option label="语义搜索" value="semantic" />
        </el-select>
        <el-input
          v-model="keyword"
          placeholder="搜索商品名称 / 描述，回车搜索"
          clearable
          style="width: 260px"
          @keyup.enter="handleSearch"
        />
        <el-select v-model="categoryId" placeholder="全部分类" clearable style="width: 140px" @change="handleSearch">
          <el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id" />
        </el-select>
        <el-button type="primary" :icon="Search" :loading="loading" @click="handleSearch">搜索</el-button>
      </div>
      <div class="toolbar-right">
        <el-badge :value="cartCount" :hidden="cartCount === 0" class="cart-badge">
          <el-button :icon="ShoppingCart" @click="$router.push('/cart')">购物车</el-button>
        </el-badge>
        <el-button :icon="Tickets" @click="$router.push('/order')">我的订单</el-button>
        <el-button type="success" :icon="CreditCard" @click="$router.push('/cart')">去结算</el-button>
      </div>
    </div>

    <el-alert type="info" :closable="false" show-icon style="margin-bottom: 16px">
      <template #title>
        支付流程体验：购物车 → 结算 → 下单 → 订单详情「立即支付」→ 模拟收银台 → 支付成功（含渠道回调 / 验签 / 幂等状态更新）。
      </template>
    </el-alert>

    <div v-loading="loading">
      <el-empty v-if="!loading && products.length === 0" description="暂无商品" />
      <el-row :gutter="16">
        <el-col v-for="p in products" :key="p.id" :span="6" style="margin-bottom: 16px">
          <el-card shadow="hover" class="product-card" :body-style="{ padding: '0' }">
            <div class="product-img">
              <el-image v-if="p.image" :src="p.image" fit="cover" class="img" />
              <div v-else class="img-placeholder">暂无图片</div>
            </div>
            <div class="product-body">
              <div class="product-name" :title="p.name">{{ p.name }}</div>
              <div class="product-meta">
                <span class="price">¥{{ Number(p.price).toFixed(2) }}</span>
                <span v-if="p.stock !== undefined" class="stock">库存 {{ p.stock }}</span>
                <el-tag v-if="p.score !== undefined" size="small" type="success">
                  相似度 {{ Number(p.score).toFixed(4) }}
                </el-tag>
              </div>
              <div class="product-actions">
                <el-input-number v-model="qtyMap[p.id]" :min="1" :max="99" size="small" />
                <el-button type="primary" size="small" :loading="addingId === p.id" @click="addToCart(p)">
                  加入购物车
                </el-button>
              </div>
            </div>
          </el-card>
        </el-col>
      </el-row>
    </div>

    <el-pagination
      v-if="total > size"
      background
      layout="total, prev, pager, next"
      :total="total"
      :page-size="size"
      :current-page="page"
      class="pager"
      @current-change="handlePageChange"
    />
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { Search, ShoppingCart, Tickets, CreditCard } from '@element-plus/icons-vue'
import { productApi, cartApi } from '../api'
import { getUser } from '../utils/auth'

const products = ref([])
const categories = ref([])
const keyword = ref('')
const searchMode = ref('keyword')
const categoryId = ref(null)
const page = ref(1)
const size = ref(12)
const total = ref(0)
const loading = ref(false)
const cartCount = ref(0)
const addingId = ref(null)

const qtyMap = reactive({})
const userId = ref(getUser()?.userId || '')

onMounted(() => {
  loadCategories()
  loadProducts()
  loadCartCount()
})

async function loadCategories() {
  try {
    const { data } = await productApi.get('/categories')
    if (data.code === 200) categories.value = data.data || []
  } catch (e) {
    // 分类加载失败不阻塞页面
  }
}

async function loadProducts() {
  loading.value = true
  try {
    if (searchMode.value === 'semantic' && keyword.value.trim()) {
      const { data } = await productApi.get('/similar', {
        params: { text: keyword.value.trim(), topK: 12 },
      })
      if (data.code === 200) {
        products.value = (data.data || []).map((r) => ({
          id: r.productId,
          name: r.name,
          price: r.price,
          image: r.image,
          stock: undefined,
          score: r.score,
        }))
        total.value = products.value.length
      }
    } else {
      const params = { page: page.value, size: size.value, status: 1 }
      if (keyword.value.trim()) params.keyword = keyword.value.trim()
      if (categoryId.value) params.categoryId = categoryId.value
      const { data } = await productApi.get('/list', { params })
      if (data.code === 200 && data.data) {
        products.value = data.data.records || []
        total.value = data.data.total || 0
      }
    }
  } catch (e) {
    ElMessage.error('加载商品失败')
  } finally {
    loading.value = false
  }
}

function handleSearch() {
  page.value = 1
  loadProducts()
}

function handlePageChange(p) {
  page.value = p
  loadProducts()
}

async function addToCart(p) {
  const qty = qtyMap[p.id] || 1
  addingId.value = p.id
  try {
    const { data } = await cartApi.post('/add', { productId: p.id, quantity: qty }, {
      headers: { 'X-User-Id': userId.value },
    })
    if (data.code === 200) {
      ElMessage.success(`「${p.name}」已加入购物车`)
      loadCartCount()
      loadProducts() // 刷新商城库存，实时反映扣减（库存以商品服务 DB 为权威源）
    } else {
      ElMessage.error(data.message || '加入购物车失败')
    }
  } catch (e) {
    ElMessage.error(e.response?.data?.message || '加入购物车失败')
  } finally {
    addingId.value = null
  }
}

async function loadCartCount() {
  try {
    const { data } = await cartApi.get('/list', { headers: { 'X-User-Id': userId.value } })
    if (data.code === 200) cartCount.value = (data.data?.items || []).length
  } catch (e) {
    // 忽略
  }
}


</script>

<style scoped>
.shop-view { padding: 20px; }

.shop-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 12px;
  margin-bottom: 16px;
}

.toolbar-left { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
.toolbar-left h2 { margin: 0; font-size: 20px; }
.toolbar-right { display: flex; align-items: center; gap: 10px; }
.cart-badge { margin-right: 8px; }

.product-card { overflow: hidden; }

.product-img {
  height: 180px;
  background: #f5f7fa;
  display: flex;
  align-items: center;
  justify-content: center;
}
.product-img .img { width: 100%; height: 100%; }
.img-placeholder { color: #c0c4cc; font-size: 13px; }

.product-body { padding: 12px; }
.product-name {
  font-weight: 600;
  font-size: 14px;
  height: 20px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
.product-meta { display: flex; align-items: center; justify-content: space-between; margin: 8px 0; }
.price { color: #f56c6c; font-size: 16px; font-weight: 600; }
.stock { color: #909399; font-size: 12px; }
.product-actions { display: flex; align-items: center; justify-content: space-between; }

.pager { margin-top: 16px; justify-content: center; }
</style>
